import { City } from '../types';

export const COLORS = {
  PRIMARY: '#003D7A',
  WHITE: '#FFFFFF',
  LIGHT_GRAY: '#F5F5F5',
  MEDIUM_GRAY: '#CCCCCC',
  DARK_GRAY: '#666666',
  ALERT_RED: '#D32F2F',
  TEXT_PRIMARY: '#000000',
  TEXT_SECONDARY: '#666666',
};

export const SPACING = {
  XS: 4,
  SM: 8,
  MD: 16,
  LG: 24,
  XL: 32,
};

export const FONT_SIZES = {
  SMALL: 14,
  BODY: 16,
  LARGE: 18,
  HEADER: 20,
  TITLE: 24,
};

export const INDIAN_CITIES: City[] = [
  { id: '1', name: 'Delhi', state: 'Delhi' },
  { id: '2', name: 'Mumbai', state: 'Maharashtra' },
  { id: '3', name: 'Bangalore', state: 'Karnataka' },
  { id: '4', name: 'Pune', state: 'Maharashtra' },
  { id: '5', name: 'Hyderabad', state: 'Telangana' },
  { id: '6', name: 'Chennai', state: 'Tamil Nadu' },
  { id: '7', name: 'Kolkata', state: 'West Bengal' },
  { id: '8', name: 'Jaipur', state: 'Rajasthan' },
  { id: '9', name: 'Lucknow', state: 'Uttar Pradesh' },
  { id: '10', name: 'Agra', state: 'Uttar Pradesh' },
  { id: '11', name: 'Indore', state: 'Madhya Pradesh' },
  { id: '12', name: 'Bhopal', state: 'Madhya Pradesh' },
  { id: '13', name: 'Nagpur', state: 'Maharashtra' },
  { id: '14', name: 'Ahmedabad', state: 'Gujarat' },
  { id: '15', name: 'Surat', state: 'Gujarat' },
  { id: '16', name: 'Vadodara', state: 'Gujarat' },
  { id: '17', name: 'Chandigarh', state: 'Chandigarh' },
  { id: '18', name: 'Kanpur', state: 'Uttar Pradesh' },
  { id: '19', name: 'Varanasi', state: 'Uttar Pradesh' },
  { id: '20', name: 'Patna', state: 'Bihar' },
  { id: '21', name: 'Ranchi', state: 'Jharkhand' },
  { id: '22', name: 'Guwahati', state: 'Assam' },
  { id: '23', name: 'Bhubaneswar', state: 'Odisha' },
  { id: '24', name: 'Thiruvananthapuram', state: 'Kerala' },
  { id: '25', name: 'Kochi', state: 'Kerala' },
  { id: '26', name: 'Kozhikode', state: 'Kerala' },
  { id: '27', name: 'Coimbatore', state: 'Tamil Nadu' },
  { id: '28', name: 'Madurai', state: 'Tamil Nadu' },
  { id: '29', name: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { id: '30', name: 'Vijayawada', state: 'Andhra Pradesh' },
  { id: '31', name: 'Mysore', state: 'Karnataka' },
  { id: '32', name: 'Mangalore', state: 'Karnataka' },
  { id: '33', name: 'Nashik', state: 'Maharashtra' },
  { id: '34', name: 'Aurangabad', state: 'Maharashtra' },
  { id: '35', name: 'Thane', state: 'Maharashtra' },
  { id: '36', name: 'Navi Mumbai', state: 'Maharashtra' },
  { id: '37', name: 'Amritsar', state: 'Punjab' },
  { id: '38', name: 'Ludhiana', state: 'Punjab' },
  { id: '39', name: 'Jalandhar', state: 'Punjab' },
  { id: '40', name: 'Dehradun', state: 'Uttarakhand' },
  { id: '41', name: 'Shimla', state: 'Himachal Pradesh' },
  { id: '42', name: 'Jammu', state: 'Jammu and Kashmir' },
  { id: '43', name: 'Srinagar', state: 'Jammu and Kashmir' },
  { id: '44', name: 'Udaipur', state: 'Rajasthan' },
  { id: '45', name: 'Jodhpur', state: 'Rajasthan' },
  { id: '46', name: 'Kota', state: 'Rajasthan' },
  { id: '47', name: 'Ajmer', state: 'Rajasthan' },
  { id: '48', name: 'Gwalior', state: 'Madhya Pradesh' },
  { id: '49', name: 'Jabalpur', state: 'Madhya Pradesh' },
  { id: '50', name: 'Raipur', state: 'Chhattisgarh' },
  { id: '51', name: 'Allahabad', state: 'Uttar Pradesh' },
  { id: '52', name: 'Meerut', state: 'Uttar Pradesh' },
  { id: '53', name: 'Ghaziabad', state: 'Uttar Pradesh' },
  { id: '54', name: 'Noida', state: 'Uttar Pradesh' },
  { id: '55', name: 'Rajkot', state: 'Gujarat' },
];
