import { RouteStop } from '../types';

interface RouteData {
  routeKey: string;
  stops: RouteStop[];
}

export const MOCK_ROUTES: RouteData[] = [
  {
    routeKey: 'Delhi-Agra',
    stops: [
      {
        id: 1,
        sequence: 1,
        stopName: 'Delhi',
        latitude: 28.7041,
        longitude: 77.1025,
        expectedTime: '09:00 AM',
        actualTime: '09:00 AM',
      },
      {
        id: 2,
        sequence: 2,
        stopName: 'Gurgaon',
        latitude: 28.4595,
        longitude: 77.0266,
        expectedTime: '10:00 AM',
        actualTime: '10:05 AM',
      },
      {
        id: 3,
        sequence: 3,
        stopName: 'Noida',
        latitude: 28.5355,
        longitude: 77.3910,
        expectedTime: '11:15 AM',
        distance: 45,
      },
      {
        id: 4,
        sequence: 4,
        stopName: 'Mathura',
        latitude: 27.4924,
        longitude: 77.6737,
        expectedTime: '01:45 PM',
        distance: 85,
      },
      {
        id: 5,
        sequence: 5,
        stopName: 'Agra',
        latitude: 27.1767,
        longitude: 78.0081,
        expectedTime: '03:30 PM',
        distance: 55,
      },
    ],
  },
  {
    routeKey: 'Delhi-Jaipur',
    stops: [
      {
        id: 6,
        sequence: 1,
        stopName: 'Delhi',
        latitude: 28.7041,
        longitude: 77.1025,
        expectedTime: '08:00 AM',
        actualTime: '08:00 AM',
      },
      {
        id: 7,
        sequence: 2,
        stopName: 'Gurgaon',
        latitude: 28.4595,
        longitude: 77.0266,
        expectedTime: '09:00 AM',
        actualTime: '09:10 AM',
      },
      {
        id: 8,
        sequence: 3,
        stopName: 'Manesar',
        latitude: 28.3551,
        longitude: 76.9318,
        expectedTime: '10:30 AM',
        distance: 50,
      },
      {
        id: 9,
        sequence: 4,
        stopName: 'Shahpura',
        latitude: 27.3936,
        longitude: 76.2230,
        expectedTime: '12:00 PM',
        distance: 75,
      },
      {
        id: 10,
        sequence: 5,
        stopName: 'Ajmer',
        latitude: 26.4499,
        longitude: 74.6399,
        expectedTime: '02:15 PM',
        distance: 95,
      },
      {
        id: 11,
        sequence: 6,
        stopName: 'Jaipur',
        latitude: 26.9124,
        longitude: 75.7873,
        expectedTime: '04:00 PM',
        distance: 65,
      },
    ],
  },
  {
    routeKey: 'Mumbai-Pune',
    stops: [
      {
        id: 12,
        sequence: 1,
        stopName: 'Mumbai',
        latitude: 19.0760,
        longitude: 72.8777,
        expectedTime: '07:00 AM',
        actualTime: '07:00 AM',
      },
      {
        id: 13,
        sequence: 2,
        stopName: 'Panvel',
        latitude: 18.9894,
        longitude: 73.1102,
        expectedTime: '08:30 AM',
        actualTime: '08:35 AM',
      },
      {
        id: 14,
        sequence: 3,
        stopName: 'Lonavala',
        latitude: 18.7537,
        longitude: 73.4076,
        expectedTime: '10:00 AM',
        distance: 60,
      },
      {
        id: 15,
        sequence: 4,
        stopName: 'Pune',
        latitude: 18.5204,
        longitude: 73.8567,
        expectedTime: '11:30 AM',
        distance: 45,
      },
    ],
  },
  {
    routeKey: 'Bangalore-Chennai',
    stops: [
      {
        id: 16,
        sequence: 1,
        stopName: 'Bangalore',
        latitude: 12.9716,
        longitude: 77.5946,
        expectedTime: '10:00 PM',
        actualTime: '10:00 PM',
      },
      {
        id: 17,
        sequence: 2,
        stopName: 'Hosur',
        latitude: 12.7409,
        longitude: 77.8253,
        expectedTime: '11:15 PM',
        actualTime: '11:20 PM',
      },
      {
        id: 18,
        sequence: 3,
        stopName: 'Krishnagiri',
        latitude: 12.5186,
        longitude: 78.2137,
        expectedTime: '12:45 AM',
        distance: 55,
      },
      {
        id: 19,
        sequence: 4,
        stopName: 'Vellore',
        latitude: 12.9165,
        longitude: 79.1325,
        expectedTime: '02:30 AM',
        distance: 70,
      },
      {
        id: 20,
        sequence: 5,
        stopName: 'Kanchipuram',
        latitude: 12.8342,
        longitude: 79.7036,
        expectedTime: '04:00 AM',
        distance: 60,
      },
      {
        id: 21,
        sequence: 6,
        stopName: 'Chengalpattu',
        latitude: 12.6922,
        longitude: 79.9763,
        expectedTime: '05:00 AM',
        distance: 40,
      },
      {
        id: 22,
        sequence: 7,
        stopName: 'Chennai',
        latitude: 13.0827,
        longitude: 80.2707,
        expectedTime: '06:30 AM',
        distance: 55,
      },
    ],
  },
  {
    routeKey: 'Kolkata-Darjeeling',
    stops: [
      {
        id: 23,
        sequence: 1,
        stopName: 'Kolkata',
        latitude: 22.5726,
        longitude: 88.3639,
        expectedTime: '06:00 AM',
        actualTime: '06:00 AM',
      },
      {
        id: 24,
        sequence: 2,
        stopName: 'Barrackpore',
        latitude: 22.7633,
        longitude: 88.3672,
        expectedTime: '07:30 AM',
        actualTime: '07:40 AM',
      },
      {
        id: 25,
        sequence: 3,
        stopName: 'Siliguri',
        latitude: 26.7271,
        longitude: 88.3953,
        expectedTime: '02:00 PM',
        distance: 550,
      },
      {
        id: 26,
        sequence: 4,
        stopName: 'Kurseong',
        latitude: 26.8807,
        longitude: 88.2747,
        expectedTime: '04:30 PM',
        distance: 48,
      },
      {
        id: 27,
        sequence: 5,
        stopName: 'Ghum',
        latitude: 27.0034,
        longitude: 88.2477,
        expectedTime: '06:00 PM',
        distance: 32,
      },
      {
        id: 28,
        sequence: 6,
        stopName: 'Sonada',
        latitude: 26.9667,
        longitude: 88.1833,
        expectedTime: '06:45 PM',
        distance: 15,
      },
      {
        id: 29,
        sequence: 7,
        stopName: 'Jorebunglow',
        latitude: 27.0333,
        longitude: 88.2500,
        expectedTime: '07:15 PM',
        distance: 12,
      },
      {
        id: 30,
        sequence: 8,
        stopName: 'Darjeeling',
        latitude: 27.0410,
        longitude: 88.2663,
        expectedTime: '08:00 PM',
        distance: 8,
      },
    ],
  },
];

export const getRouteStops = (fromCity: string, toCity: string): RouteStop[] => {
  const routeKey = `${fromCity}-${toCity}`;
  const route = MOCK_ROUTES.find((r) => r.routeKey === routeKey);
  
  if (route) {
    return route.stops;
  }
  
  return [
    {
      id: 100,
      sequence: 1,
      stopName: fromCity,
      latitude: 0,
      longitude: 0,
      expectedTime: '09:00 AM',
      actualTime: '09:00 AM',
    },
    {
      id: 101,
      sequence: 2,
      stopName: `${fromCity} Outskirts`,
      latitude: 0,
      longitude: 0,
      expectedTime: '10:00 AM',
      actualTime: '10:05 AM',
    },
    {
      id: 102,
      sequence: 3,
      stopName: 'Midway Stop',
      latitude: 0,
      longitude: 0,
      expectedTime: '12:00 PM',
      distance: 75,
    },
    {
      id: 103,
      sequence: 4,
      stopName: `${toCity} Outskirts`,
      latitude: 0,
      longitude: 0,
      expectedTime: '02:00 PM',
      distance: 80,
    },
    {
      id: 104,
      sequence: 5,
      stopName: toCity,
      latitude: 0,
      longitude: 0,
      expectedTime: '03:30 PM',
      distance: 45,
    },
  ];
};

export const getCurrentStopIndex = (): number => {
  return 2;
};
